### PR TITLE
Update jacodb and refine dataflow accordingly

### PR DESCRIPTION
**Pull request by Lipen**
This PR updates jacodb to the latest `neo` branch version and also fixes/improves dataflow accordingly to API changes in jacodb.

Also a major change is that `Traits` now contain _only functions_. The reason for this is that functions look much more consistent than a combination of extension properties and functions.

### CODE REVIEW

**Comment by Lipen** [comment]
@CaelmBleidd should we also rename `usvm-jvm-dataflow` to a more logical `usvm-dataflow-jvm` (JVM-specific dataflow) in this PR, since we are going to add `usvm-dataflow-ts` in the future? Or we need a separate PR for this?

**Review by Saloed — APPROVED** [review]

**Review by Saloed — CHANGES_REQUESTED** [review]
Initialization failed in many tests:
```
JcCallGraphStatisticsTests > initializationError FAILED
    java.lang.IllegalStateException at JcCallGraphStatisticsTests.kt:14
```

**Comment by Lipen** [comment]
```
This extension requires `Usages` feature to be installed
java.lang.IllegalStateException: This extension requires `Usages` feature to be installed
	at org.jacodb.impl.features.JcUsages.usagesExt(UsagesExtension.kt:140)
	at org.usvm.machine.JcApplicationGraph$jcApplicationGraph$1.invokeSuspend(JcApplicationGraph.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.usvm.machine.JcApplicationGraph.<init>(JcApplicationGraph.kt:21)
	at org.usvm.machine.JcCallGraphStatisticsTests.<init>(JcCallGraphStatisticsTests.kt:14)
...
```

```java
suspend fun JcClasspath.usagesExt(): SyncUsagesExtension {
    if (!db.isInstalled(Usages)) {
        throw IllegalStateException("This extension requires `Usages` feature to be installed")
    }
    return SyncUsagesExtension(hierarchyExt(), this)
}
```

**Comment by Lipen** [comment]
Seems like `cp: JcClasspath` that is passed to `JcApplicationGraphImpl` in tests is actually from the `JacoDBContainer`, where only `InMemoryHierarchy` feature is installed. I've added `Usages` feature here, tests pass locally (_except the approximation tests, as expected_), but probably @Saloed have to double-check whether it is correct.

**Review by Saloed — APPROVED** [review]

**Pull request merged**
